# Generated by Django 6.0.4 on 2026-04-17 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_appuser_comment'),
    ]

    operations = [

    ]