# Generated by Django 6.0.4 on 2026-04-17 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20260417_1007'),
    ]


    def create_app_user(apps, schema_editor):
        # We get the model from the versioned app registry;
        # if we directly import it, it'll be the wrong version
        AppUser = apps.get_model("website", "AppUser")
        db_alias = schema_editor.connection.alias
        AppUser.objects.using(db_alias).bulk_create([
            AppUser(first_name="Les", last_name="Wilson", image_url="img1.jpg", email="test@email.com", password="test123", location="Edinburgh"),
            AppUser(first_name="John", last_name="Smith", image_url="img2.jpg", email="test1@email.com", password="test123", location="London"),
        ])

    def delete_app_user(apps, schema_editor):
        # forwards_func() creates two Country instances,
        # so reverse_func() should delete them.
        AppUser = apps.get_model("website", "AppUser")
        db_alias = schema_editor.connection.alias
        AppUser.objects.using(db_alias).filter(email="test@email.com").delete()
        AppUser.objects.using(db_alias).filter(email="test1@email.com").delete()

    operations = [
        migrations.RunPython(create_app_user, delete_app_user),
    ]